# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d76d8773f1db20d83ef309404433742e2e64ca41f19f536cb382deba21cadb11b67a14363c769be33e1e244759a40e1b29317acfaf8e88c232dc35e8f160c78c

test:
  secret_key_base: 43cbfe83f63c6bd88812cfa06539c484d9916c60326a28f0842089ff8b11079580772b6bb92b52678631d0191d04a4fabeb87bb7b3700fd2f358198eb358ade9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
